baseurl = "https://www.arti-s.com"
languageCode = "en-us"
theme = "stack"
title = "Arti-s homepage"
copyright = "Artjom Schwenk"

[params.Sidebar]
emoji = "🐍"

[sidebar.avatar]
src = "img/avatar.png"

[[menu.social]]
  identifier = "github"
  name = "Github"
  weight = -100
  url = "https://github.com/ArtjomSchwenk"
  [menu.social.params]
    icon = "brand-github"

[[menu.social]]
  identifier = "mastodon"
  name = "Mastodon"
  weight = -90
  url = "https://urusai.social/@stevy"
  [menu.social.params]
    icon = "brand-mastodon"

[[menu.social]]
  identifier = "bluesky"
  name = "Bluesky"
  weight = -80
  url = "https://bsky.app/profile/arti-s.bsky.social"
  [menu.social.params]
    icon = "brand-bluesky"

[[menu.social]]
  identifier = "matrix"
  name = "Matrix"
  weight = -70
  url = "https://matrix.to/#/@arti-s:matrix.org?client=im.element"
  [menu.social.params]
    icon = "brand-matrix"

[[menu.social]]
  identifier = "mail"
  name = "contact@arti-s.com"
  weight = -60
  url = "mailto:contact@arti-s.com"
    [menu.social.params]
      icon = "mail"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = "-100"
  [menu.main.params]
    icon = "home"

[footer]
  since = 2024

[params.article.license]
  enabled = true
  default = "Licensed under CC BY-NC-SA 4.0"
