baseurl = "https://example.com"
languageCode = "en-us"
theme = "stack"
title = "Arti-S homepage"
copyright = "Artjom Schwenk"

[Params.Sidebar]
emoji = "🐍"

[Params.Sidebar.avatar]
enabled = true
src = "img/avatar.png"
local = true

[[menu.social]]
  identifier = "github"
  name = "Github"
  weight = -100
  url = "https://github.com/ArtjomSchwenk"
  [menu.social.params]
    icon = "brand-github"

[[menu.social]]
  identifier = "mastodon"
  name = "Mastodon"
  weight = -90
  url = "https://urusai.social/@stevy"
  [menu.social.params]
    icon = "brand-mastodon"

[[menu.social]]
  identifier = "matrix"
  name = "Matrix"
  weight = -80
  url = "https://matrix.to/#/@arti-s:matrix.org?client=im.element"
  [menu.social.params]
    icon = "brand-matrix"

[[menu.social]]
  identifier = "mail"
  name = "Mail"
  weight = -70
  url = "mailto:contact@arti-s.com"
    [menu.social.params]
      icon = "mail"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = "-100"
  [menu.main.params]
    icon = "home"

[Params.Footer]
  since = 2024

[Params.Article]
  math = true
  [params.article.licence]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"
